# Generated by Django 4.0.4 on 2022-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('stock_symbol', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('employees', models.CharField(blank=True, max_length=255, null=True)),
                ('sales', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('company_name', models.CharField(max_length=255)),
                ('stock_symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price_date', models.DateField()),
                ('open', models.CharField(blank=True, max_length=255, null=True)),
                ('high', models.CharField(blank=True, max_length=255, null=True)),
                ('low', models.CharField(blank=True, max_length=255, null=True)),
                ('close', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'price_history',
                'managed': False,
            },
        ),
    ]
